create table songs 
(
  song_id integer primary key generated by default as identity,
  song_name varchar(100) default 'no song title',
  album_name varchar(100) default 'no album name',
  artist integer references artists(artist_id)
)