create table artists (
  artist_id integer primary key generated by default as identity,
  artist_name varchar(255) not null unique,
  birthday date not null,
  birthplace varchar(255) not null,
  is_alive boolean not null default 'true'
)